### ISSUE TITLE
wait-for-postgress container in migrate pod does not pick externalDatabase.existingSecret

### ISSUE THREAD

**Issue by neeraj-ec** [AlexandreBrg/openfga-helm#13]
Chart version: `v0.3.2`
App version: `v0.3.1`

migrate pod stuck in pending state if using `externalDatabase.existingSecret`.

``` yaml 
externalDatabase:
  existingSecret: "openfga-secrets"
  existingSecretKey: "OPENFGA_DATASTORE_URI"
```

migrate pod stuck with following error.
``` log
nc: bad address ''
Waiting for postgres...
nc: bad address ''
Waiting for postgres...
nc: bad address ''
Waiting for postgres...
nc: bad address ''
Waiting for postgres...
nc: bad address ''
```
