### ISSUE TITLE
Feature: implement job to apply openfga migrations

### ISSUE THREAD

**Issue by alexandrebrg** [AlexandreBrg/openfga-helm#3]
Run openfga migrate when running with postgres persistency

**Comment by neeraj-ec** [comment]
Can we do it with [`initContainers`](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use)? I tried to solve it like this:

``` yaml
    spec:
      containers:
        - image: openfga/openfga
          name: openfga
          ports:
            - containerPort: 3000
              name: playground
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
          envFrom:
            - configMapRef:
                name: openfga-configs
            - secretRef:
                name: openfga-secrets
          readinessProbe:
            httpGet:
              path: healthz
              port: http
      initContainers:
        - image: openfga/openfga
          name: migrations
          command: ["migrate"]
          envFrom:
            - configMapRef:
                name: openfga-configs
            - secretRef:
                name: openfga-secrets
```

Though it didn't work somehow. 😄 I do not have much expertise in kubernetes.
