### ISSUE TITLE
Using externalDatabase.existingSecret gives error

### ISSUE THREAD

**Issue by neeraj-ec** [AlexandreBrg/openfga-helm#4]
Hi @AlexandreBrg thanks for making this useful helm chart. It was a great time saver for me.
There seems to be an issue while using `externalDatabase.existingSecret` value in `values.yaml`.

#### Helm command
``` bash
helm install authz openfga/openfga --namespace dev --values values.yaml
```

#### values.yaml
``` yaml
playground:
  enabled: true

service:
  playground:
    enabled: true
  
persistencyMode: postgres

## @param externalDatabase.existingSecret Name of an existing secret resource containing the database uri
## @param externalDatabase.existingSecretKey Name of an existing secret key containing the database uri
##
externalDatabase:
  existingSecret: "openfga-secrets"
  existingSecretKey: "OPENFGA_DATASTORE_URI"
```

#### Error:
``` log
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. 
Unable to continue with install: Secret "openfga-secrets" in namespace "dev" exists and cannot be imported into the current release: 
invalid ownership metadata; 
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "authz"; 
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dev"
```
Though manually I can set these labels and annotation to the secret  `openfga-secrets` I created but ideally it should work without setting those annotations also.
